// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrMXWukqusnI5kbW0VrC-inmRC8FcuiA8',
    appId: '1:124232076338:web:3548b2bbed126795e6402b',
    messagingSenderId: '124232076338',
    projectId: 'flutix-a536f',
    authDomain: 'flutix-a536f.firebaseapp.com',
    storageBucket: 'flutix-a536f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrW_36JNRLmS9uPriA8Q4o-sR9d3siNM0',
    appId: '1:124232076338:android:8eeae351e3bc06a4e6402b',
    messagingSenderId: '124232076338',
    projectId: 'flutix-a536f',
    storageBucket: 'flutix-a536f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyNHbZ09g1EY9bAimmEA4Le3vQtOZuwR8',
    appId: '1:124232076338:ios:b20f8c72d2ef61d5e6402b',
    messagingSenderId: '124232076338',
    projectId: 'flutix-a536f',
    storageBucket: 'flutix-a536f.appspot.com',
    iosBundleId: 'com.example.flutixHomeMenu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyNHbZ09g1EY9bAimmEA4Le3vQtOZuwR8',
    appId: '1:124232076338:ios:3ac32537f80c6222e6402b',
    messagingSenderId: '124232076338',
    projectId: 'flutix-a536f',
    storageBucket: 'flutix-a536f.appspot.com',
    iosBundleId: 'com.example.flutixHomeMenu.RunnerTests',
  );
}
